version: "3.9"

services:
  web:
    image: node:20-alpine
    container_name: web-dev
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
      NEXT_PUBLIC_APP_NAME: "Verifier"
      SESSION_COOKIE_NAME: "verifier_session"
      JWT_SECRET: "dev-secret-change-me"
      ELASTICSEARCH_NODE: "http://es:9200"
      AUSPOST_API_KEY: "${AUSPOST_API_KEY}"
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      es:
        condition: service_healthy

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata-dev:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  esdata-dev:
