version: "3.9"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 30

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      es:
        condition: service_healthy
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_URL: "http://web:3000"
      NEXT_PUBLIC_APP_NAME: "Verifier"
      SESSION_COOKIE_NAME: "verifier_session"
      JWT_SECRET: "change-me-super-long"
      ELASTICSEARCH_NODE: "http://es:9200"
      AUSPOST_API_KEY: "${AUSPOST_API_KEY}"
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}"
    ports:
      - "3000:3000"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    depends_on:
      es:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"

volumes:
  esdata:
